#!/usr/bin/env bash
# disable-services
# A wrapper that makes any module running inside it not start services once then are installed
# Written by Guy Sheffer <guysoft at gmail dot com> and Gina Häußge <osd@foosel.net>
# GPL V3
########
set -ex 

rm -r /usr/sbin/policy-rc.d 
