#!/usr/bin/env bash
# disable-services
# A wrapper that makes any module running inside it not start services once then are installed
# Written by Guy Sheffer <guysoft at gmail dot com> and Gina Häußge <osd@foosel.net>
# GPL V3
########
set -ex

source /common.sh
install_cleanup_trap

apt-get update --allow-relreaseinfo-change --allow-releaseinfo-change
if [ $( is_in_apt policykit-1 ) -eq 1 ]; then
  sudo apt-get -y install policykit-1
fi

# prevent any installed services from automatically starting
echo exit 101 > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d
