#!/usr/bin/env bash
# disable-services
# A wrapper that makes any module running inside it not start services once then are installed
# Written by Guy Sheffer <guysoft at gmail dot com> and Gina Häußge <osd@foosel.net>
# GPL V3
########

source /common.sh
install_cleanup_trap

# prevent any installed services from automatically starting
echo exit 101 > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d
