#!/usr/bin/env bash
# Base script
# Basic and manditory settings for the base of a CustomPiOS build
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########
set -ex

if [ -n "$BASE_APT_PROXY" ]
then
  rm -r /etc/apt/apt.conf.d/02octopi_build_proxy
fi

if [ -n "$BASE_PYPI_INDEX" ]
then
  rm -r /root/.pip
  rm -r /root/.pydistutils.cfg
  rm -r /home/pi/.pip/pip.conf
  rm -r /home/pi/.pydistutils.cfg
fi

#reach device by name
if [ -f /etc/hostname ]; then
    read FILE_HOST_NAME < /etc/hostname
        FILE_HOST_NAME=${FILE_HOST_NAME//$'\n'/}
    else
	    FILE_HOST_NAME=raspberrypi
fi

echo "$BASE_OVERRIDE_HOSTNAME" > /etc/hostname
sed -i -e "s@${FILE_HOST_NAME}@$BASE_OVERRIDE_HOSTNAME@g" /etc/hosts
