#!/usr/bin/env bash
# Base script
# Basic and manditory settings for the base of a CustomPiOS build
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########
if [ -n "$BASE_APT_PROXY" ]
then
  rm -r /etc/apt/apt.conf.d/02octopi_build_proxy
fi

if [ -n "$BASE_PYPI_INDEX" ]
then
  rm -r /root/.pip
  rm -r /root/.pydistutils.cfg
  rm -r /home/pi/.pip/pip.conf
  rm -r /home/pi/.pydistutils.cfg
fi

#reach device by name
echo "$BASE_OVERRIDE_HOSTNAME" > /etc/hostname
sed -i -e "s@raspberrypi@$BASE_OVERRIDE_HOSTNAME@g" /etc/hosts
