#!/usr/bin/env bash
[ -n "$KERNEL_TYPE" ] || KERNEL_TYPE=both
[ -n "$KERNEL_CONFIG_APPEND" ] || KERNEL_CONFIG_APPEND=""
[ -n "$KERNEL_COMMIT" ] || KERNEL_COMMIT=rpi-4.9.y
[ -n "$KERNEL_URL" ] || KERNEL_URL="https://github.com/raspberrypi/linux/archive"
[ -n "$KERNEL_SOURCE_CLEANUP" ] || KERNEL_SOURCE_CLEANUP="no"

