#!/bin/bash
#
# This script is part of the CustomPiOS admin-toolkit module

UFW_PORTS_UDP=no
UFW_PORTS_TCP=no
UFW_ENABLE_LOGGING=no

if [ ! -f /etc/ufw_enabled ];
then
    ufw enable
    ufw default deny incoming
    ufw allow OpenSSH
    
    if [ "$UFW_PORTS_UDP" != 'no' ];
    then
        ufw allow "${UFW_PORTS_UDP}"/udp
    fi
    
    if [ "$UFW_PORTS_TCP" != 'no' ];
    then
        ufw allow "${UFW_PORTS_TCP}"/tcp
    fi

    if ["$UFW_ENABLE_LOGGING" == 'yes']
    then
        sudo ufw logging on
    fi

    touch /etc/ufw_enabled
fi
