#!/usr/bin/env bash
set -x
set -e
# NodeJS
# Install nodejs on a raspberrypi
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3

export LC_ALL=C

pushd /home/pi
    wget https://nodejs.org/dist/v${NODEJS_VERSION}/node-v${NODEJS_VERSION}-linux-armv6l.tar.gz
    tar -xzf node-v${NODEJS_VERSION}-linux-armv6l.tar.gz
    ln -s /home/pi/node-v${NODEJS_VERSION}-linux-armv6l/bin/node /usr/local/bin
    ln -s /home/pi/node-v${NODEJS_VERSION}-linux-armv6l/bin/npm /usr/local/bin
popd
