#!/usr/bin/env bash
# 
#  Admin toolkit for securing your pi. 
#  Make sure you have the config file setup.
# 
#  Written by asdfinit
#  GPL V3
########
set -x
set -e

source /common.sh
install_cleanup_trap

#####################################################################
### Add a user if in config
if [ "$ADMIN_NAME" != "default" ]
then

    # add user
    if [ "$ADMIN_FULLNAME" != "no" ]
    then
        echo "Adding user $ADMIN_NAME with GECOS fields"
        useradd -m -s $(which bash) -G sudo,adm "${ADMIN_NAME}" -c "${ADMIN_FULLNAME}"
    else
        echo "Adding user $ADMIN_NAME"
        useradd -m -s $(which bash) -G sudo,adm "${ADMIN_NAME}"
    fi

    # check for override password
    if [ "$ADMIN_PASSWORD" != "default" ]
    then
        echo "${ADMIN_NAME}:${ADMIN_PASSWORD}" | chpasswd
    else
        echo "${ADMIN_NAME}:raspberry" | chpasswd
    fi

    # check for ssh key install and do other ssh things
    if [ "$ADMIN_SSH" != "default" ]
    then
        echo "Installign ssh key"
        mkdir -p /home/"${ADMIN_NAME}"/.ssh
        echo "${ADMIN_SSH}" > /home/"${ADMIN_NAME}"/.ssh/authorized_keys
        chown -R "${ADMIN_NAME}" /home/"${ADMIN_NAME}"/.ssh
        chmod 775 /home/"${ADMIN_NAME}"/.ssh
        chmod 600 /home/"${ADMIN_NAME}"/.ssh/authorized_keys

        # disable ssh password
        if [ "$ADMIN_SSH_NO_PASS" == "yes" ]
        then
            echo "disabling password ssh"
            sed -i /etc/ssh/sshd_config -e "s/^ChallengeResponseAuthentication yes/ChallengeResponseAuthentication no/"
            sed -i /etc/ssh/sshd_config -e "s/^#PasswordAuthentication yes/PasswordAuthentication no/"
            sed -i /etc/ssh/sshd_config -e "s/^UsePAM yes/UsePAM no/"
            sed -i /etc/ssh/sshd_config -e "s/^#PubkeyAuthentication yes/PubkeyAuthentication yes/"
            sed -i /etc/ssh/sshd_config -e "s/^#PermitEmptyPasswords no/PermitEmptyPasswords no/"
        fi
    
    fi

    # only allow created user to ssh
    if [ "$ADMIN_SSH_ALLOW_ONLY_CREATED_USER" == "yes" ]
    then 
        echo "Adding user to ssh allow list"
        echo "AllowUsers ${ADMIN_NAME}" >> /etc/ssh/sshd_config
    fi

    # pi no sudo
    if [ "$ADMIN_PI_NO_SUDO" == "yes" ]
    then
        echo "Removing pi from the sudoers group"
        delgroup pi sudo
        rm /etc/sudoers.d/010_pi-nopasswd
    fi

    # Add hostname change script
    if [ "$ADMIN_HOSTNAME_CHANGE_SCRIPT" == "yes" ]
    then
        unpack /filesystem/tools /home/"${ADMIN_NAME}" ${ADMIN_NAME}
        chmod +x /home/"${ADMIN_NAME}"/hostname_change.sh
    fi

fi 
# End User section

# Begin general section
if [ "$ADMIN_UPDATE_PACKAGES" == "yes" ]
then
    apt-get update && apt-get upgrade -y
fi

# Install packages if listed
if [ "$ADMIN_INSTALL_LIST" != "no" ]
then
    apt-get install ${ADMIN_INSTALL_LIST} -y
fi

# Install UFW Firewall if wanted
if [ "$ADMIN_UFW_INSTALL" == "yes" ]
then
    apt-get install ufw -y
    unpack /filesystem/root_init /
    unpack /filesystem/home/pi /home/pi pi
    chmod +x /home/pi/scripts/ufw_config
    systemctl enable ufw_config.service
    if [ "$ADMIN_UFW_PORTS_UDP" != "no" ]
    then
        sed -i /home/pi/ufw_config -e "s/^ADMIN_UFW_PORTS_UDP=no/ADMIN_UFW_PORTS_UDP=${ADMIN_UFW_PORTS_UDP}/"
    fi
    if [ "$ADMIN_UFW_PORTS_TCP" != "no" ]
    then
        sed -i /home/pi/ufw_config -e "s/^ADMIN_UFW_PORTS_TCP=no/ADMIN_UFW_PORTS_TCP=${ADMIN_UFW_PORTS_TCP}/"
    fi

    if [ "$ADMIN_UFW_ENABLE_LOGGING" == "yes" ]
    then
        sed -i /home/pi/ufw_config -e "s/^ADMIN_UFW_ENABLE_LOGGING=no/ADMIN_UFW_ENABLE_LOGGING=yes/"
    fi
fi

# Remove Network Manager(fix for wifi random mac address)
if [ "$ADMIN_REMOVE_NETWORK_MANAGER" == "yes" ]
then
    sudo apt-get remove network-manager -y
fi