#!/usr/bin/env bash
# CustomPiOS usage-statistics module
# Send anonymous statistics of a distro
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########

# URL to the tracking server
[ -n "$USAGE_STATISTICS_URL" ] || USAGE_STATISTICS_URL=https://custompios-tracking.gnethomelinux.com

# The file name that holds the distro version
[ -n "$USAGE_STATISTICS_VERSION_FILE" ] || USAGE_STATISTICS_VERSION_FILE=/etc/${DIST_NAME,,}_version

# The file name that holds the distro version
[ -n "$USAGE_STATISTICS_VARIANT_FILE" ] || USAGE_STATISTICS_VARIANT_FILE=/etc/dist_variant
