#!/usr/bin/env bash
# CustomPiOS wireless-powersave-off module
# Script sets that makes sure that wifi powersave is off: https://github.com/guysoft/OctoPi/issues/721
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########
set -x
set -e

source /common.sh


# Turn off wlan power management
sed -i 's@exit 0@@' /etc/rc.local
cat <<'EOT' >> /etc/rc.local
echo "Disabling power management for wlan0" 
iw dev wlan0 set power_save off
EOT

echo 'exit 0' >> /etc/rc.local
