#!/usr/bin/env bash
# CustomPiOS module : docker
# Original script written by Damien DALY (https://github.com/MaitreDede/)
# GPL V3
########
set -ex

source /common.sh
install_cleanup_trap

curl -sSL get.docker.com | sh && usermod pi -aG docker

#cleanup
apt-get clean
apt-get autoremove -y