#!/usr/bin/env bash
# CustomPiOS module : docker
# Original script written by Damien DALY (https://github.com/MaitreDede/)
# Changes by Guy Sheffer
# GPL V3
########
set -ex

source /common.sh
install_cleanup_trap

if [ "${BASE_DISTRO}" == "raspbian" ]; then
        curl -sSL get.docker.com | sh
elif [ "${BASE_DISTRO}" == "ubuntu" ]; then
    if [ "${BASE_ARCH}" == "aarch64" ] || [ "${BASE_ARCHi}" == "arm64" ]; then
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu disco stable"
    else
        echo "Error, not implemented Ubuntu 32bit"
	exit 1
    fi
    apt-get update
    apt-get install -y docker-ce
fi

if [ "${DOCKER_ADD_USER_TO_GROUP}" == "yes" ]; then
    usermod "${BASE_USER}" -aG docker
fi

if [ "${DOCKER_COMPOSE}" == "yes" ]; then
    apt-get install -y python3 python3-distutils python3-dev python3-testresources gcc libffi-dev build-essential libssl-dev
    # Docker-compose
    wget https://bootstrap.pypa.io/get-pip.py -O - | python3
    pip3 install --ignore-installed PyYAML
    pip3 install docker-compose
fi

#cleanup
apt-get clean
apt-get autoremove -y
