#!/usr/bin/env bash
# VlcOS generation script
########
set -x
set -e

source /common.sh
install_cleanup_trap

#set up gui service
sed -i 's/#user-session=.*/user-session=guisession/g' /etc/lightdm/lightdm.conf
# This is now down as a systemd service to handle username conf on boot
sed -i 's/#autologin-user=.*/autologin-user=UID_1000_PLACEHOLDER/g' /etc/lightdm/lightdm.conf
systemctl enable update_lightdm_conf.service

# set the gui to run the main script of the GUI session
sed -i "s@GUI_SESSION_PLACEHOLDEFR@${GUI_STARTUP_SCRIPT}@g" /opt/custompios/scripts/start_gui

rm -r /usr/sbin/policy-rc.d || true
