#!/usr/bin/env bash
#Shebang for better file detection
#### headless_nm install module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2024 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

set -Ee

export LC_ALL=C

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

# Install dependencies
apt-get update
# shellcheck disable=SC2086
apt-get install -y ${HEADLESS_NM_DEPS}

# Install scripts
unpack filesystem/usr/local/bin /usr/local/bin root
unpack filesystem/boot /boot root
unpack filesystem/etc /etc root

#Enable network-manager service
systemctl_if_exists enable NetworkManager.service

# Enable Service
systemctl_if_exists enable headless_nm.service

# set OS_NAME in Wifi-README.txt according to DIST_NAME
if [ -f "/boot/WiFi-README.txt" ]; then
    sed -i 's|OS_NAME|'"${DIST_NAME}"'|g' /boot/WiFi-README.txt
fi
