#!/usr/bin/env bash
# Network
# Adds to /boot configuration files that let you set up wifi network before booting
# Written by Guy Sheffer <guysoft at gmail dot com> and Gina Häußge <gina@octoprint.org>
# GPL V3
########
set -x
set -e

export LC_ALL=C

source /common.sh
install_cleanup_trap

unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot
unpack /filesystem/root /

DIST_NETWORK_FILE=/boot/${DIST_NAME,,}-wpa-supplicant.txt

# allow configuring multiple wifi networks via /boot/DIST_NAME-wpa-supplicant.txt
mv /boot/custompios-wpa-supplicant.txt ${DIST_NETWORK_FILE}
cat /etc/wpa_supplicant/wpa_supplicant.conf >> ${DIST_NETWORK_FILE}  # append distributed conf to our own
rm -f /etc/wpa_supplicant/wpa_supplicant.conf                        # remove distributed conf
ln -s ${DIST_NETWORK_FILE} /etc/wpa_supplicant/wpa_supplicant.conf   # create symlink

# copy /etc/wpa_supplicant/ifupdown.sh to /etc/ifplugd/action.d/ifupdown - for wlan auto reconnect
[ -f /etc/ifplugd/action.d/ifupdown ] && mv /etc/ifplugd/action.d/ifupdown /etc/ifplugd/action.d/ifupdown.original
[ -f /etc/wpa_supplicant/ifupdown.sh ] && ln -s /etc/wpa_supplicant/ifupdown.sh /etc/ifplugd/action.d/ifupdown

# prevent ntp updates from failing due to some Rpi3 weirdness, see also "Fix SSH" further below
sed -i 's@exit 0@@' /etc/rc.local
echo '/sbin/iptables -t mangle -I POSTROUTING 1 -o wlan0 -p udp --dport 123 -j TOS --set-tos 0x00' >> /etc/rc.local
echo 'exit 0' >> /etc/rc.local


