#!/usr/bin/env bash
# 
# Copyright 2021 by Stephan Wendel aka KwadFan
# <me@stephanwe.de>
# This file may distributed under GPLv3
########

### Cleanup
if [ "${PKGUPGRADE_CLEANUP}" = "y" ]; then
    apt clean -y
    apt autoclean -y
fi

