#!/usr/bin/env bash
set -x
set -e
# This module enables the raspicam
echo "# enable raspicam" >> /"${BASE_BOOT_MOUNT_PATH}"/config.txt
echo "start_x=1" >> /"${BASE_BOOT_MOUNT_PATH}"/config.txt
echo "gpu_mem=128" >> /"${BASE_BOOT_MOUNT_PATH}"/config.txt
