#!/bin/bash

# Stop the screen from turning off when idle.
DISABLE_POWER_MANAGEMENT=yes

# Rotate screen if needed, see 'xrandr -h' for options.
DISPLAY_ORIENTATION=normal

if ["${DISPLAY_ORIENTATION}" != 'normal'];
then
  xrandr --orientation ${DISPLAY_ORIENTATION}
fi

if ["${DISABLE_POWER_MANAGEMENT}" == 'yes'];
then
  xset s off         # don't activate screensaver
  xset -dpms         # disable DPMS (Energy Star) features.
  xset s noblank     # don't blank the video device
fi

matchbox-window-manager &

GUI_SESSION_PLACEHOLDEFR
