#!/usr/bin/env bash
set -e
set -x
echo "Distro path: ${DIST_PATH}"
echo "CustomPiOS path: ${CUSTOM_PI_OS_PATH}"
echo "================================================================"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
${DIR}/build $1
