#!/usr/bin/env bash
set -e


usage() {
	cat <<EOF
usage: $0 [OPTIONS] [<variant>]

	builds the current distro

OPTIONS
	-l <logfile>	write build-log to given file (instead of ${LOG:-build.log}
	-h	print this help and exit

EOF

}

while getopts "hl:" opt; do
	case "$opt" in
		h)
			usage
			exit 0
			;;
		l)
			export LOG="$OPTARG"
			;;
		?)
			usage
			exit 2
			;;
	esac
done
shift $(($OPTIND - 1))

echo "Distro path: ${DIST_PATH}"
echo "CustomPiOS path: ${CUSTOM_PI_OS_PATH}"
echo "================================================================"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


set -x

${DIR}/build "$1"
