#!/usr/bin/env bash

set -e

set -x

[ -n "$LOG" ] || LOG="build.log"

define(){ IFS='\n' read -r -d '' ${1} || true; }

define SCRIPT <<'EOF'
CUSTOM_OS_PATH=$(dirname $(realpath -s $0))
CONFIG_FILE="${CUSTOM_PI_OS_PATH}/config"

if [ -f "$CONFIG_FILE" ]; then
    BASE_BOARD_FROM_CONFIG=$(bash -c "source \"$CONFIG_FILE\" >/dev/null 2>&1; echo \$BASE_BOARD")
    if [ -n "$BASE_BOARD_FROM_CONFIG" ]; then
        export BASE_BOARD="$BASE_BOARD_FROM_CONFIG"
        echo "BASE_BOARD set to ${BASE_BOARD} from ${CONFIG_FILE} before generating board config."
    else
        echo "BASE_BOARD not found in ${CONFIG_FILE}."
    fi
else
    echo "Config file ${CONFIG_FILE} does not exist."
fi

export EXTRA_BOARD_CONFIG=$(mktemp)
${BUILD_SCRIPT_PATH}/custompios_core/generate_board_config.py "${EXTRA_BOARD_CONFIG}"
echo "Temp source file: ${EXTRA_BOARD_CONFIG}"

source ${BUILD_SCRIPT_PATH}/common.sh
install_cleanup_trap

source ${CUSTOM_PI_OS_PATH}/config "${1}" "${EXTRA_BOARD_CONFIG}" ${@}
${CUSTOM_PI_OS_PATH}/config_sanity

[ "$CONFIG_ONLY" == "yes" ] || source ${CUSTOM_OS_PATH}/custompios ${@}
EOF

if [ "$LOG" != "no" ]; then
    touch "$LOG"
    chmod 666 "$LOG"
    eval "$SCRIPT" 2>&1 | tee "$LOG"
    exit ${PIPESTATUS}
else
    eval "$SCRIPT"
fi
