#!/usr/bin/env bash

set -e

set -x

[ -n "$LOG" ] || LOG="build.log"

define(){ IFS='\n' read -r -d '' ${1} || true; }

define SCRIPT <<'EOF'
BUILD_SCRIPT_PATH=$(dirname $(realpath -s $BASH_SOURCE))
export EXTRA_BAORD_CONFIG=$(mktemp)
${BUILD_SCRIPT_PATH}/custompios-core/generate_board_config.py "${EXTRA_BAORD_CONFIG}"
echo "Temp source file: ${EXTRA_BAORD_CONFIG}"

source ${BUILD_SCRIPT_PATH}/common.sh
install_cleanup_trap

CUSTOM_OS_PATH=$(dirname $(realpath -s $0))

source ${CUSTOM_PI_OS_PATH}/config ${1} "${EXTRA_BAORD_CONFIG}" ${@}
${CUSTOM_PI_OS_PATH}/config_sanity

[ "$CONFIG_ONLY" == "yes" ] || source ${CUSTOM_OS_PATH}/custompios ${@}
EOF

if [ "$LOG" != "no" ]; then
    touch "$LOG"
    chmod 666 "$LOG"
    eval "$SCRIPT" 2>&1 | tee "$LOG"
    exit ${PIPESTATUS}
else
    eval "$SCRIPT"
fi
