#!/usr/bin/env bash
set -x
echo "Distro path: ${DIST_PATH}"
echo "CustomPiOS path: ${CUSTOM_PI_OS_PATH}"
echo "================================================================"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
${DIR}/build $1
exit_code=$?
if [ $exit_code -ne 0 ]; then
    exit $exit_code
fi
