#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/argparse.bash" || exit 1
argparse "$@" <<EOF || exit 1

parser.add_argument('dest', help="The destination folder")
parser.add_argument('-g', '--get_image', action='store_true',
                    help='Pick a number [default %(default)s]')
EOF

echo Settings: 
echo making dstro in "$DEST"

DIST_NAME=$(basename "$DEST")

for a in "${MULTIPLE[@]}"; do
    echo "  $a"
done

if [ -d ${DEST} ]; then
    echo "Error, folder already exists: ${DEST}"
    exit 1
fi

if [ -f ${DEST} ]; then
    echo "Error, file already exists: ${DEST}"
    exit 1
fi

cp -a ${DIR}/dist_generators/dist_example "${DEST}"
chown $USER:$USER -R ${DEST}

${DIR}/dist_generators/dist_example_script "${DEST}"

"$DIR/update-custompios-paths" "${DEST}/src"

if [ $GET_IMAGE ]; then
    echo "Downloading latest Raspbian image"
    
    CURRENT_RASPBIAN=$(curl https://downloads.raspberrypi.org/raspios_lite_armhf/images/ | grep raspios | tail -n 1 | awk -F "href=\"" '{print $2}' | awk -F "/" '{print $1}')
    if [ $? -ne 0 ]; then
        echo "error getting date"
        exit 1
    fi
    CURRENT_RASPBIAN_FILE=$(curl http://downloads.raspberrypi.org/raspios_lite_armhf/images/${CURRENT_RASPBIAN}/ | grep .xz | head -n 1 | awk -F "href=\"" '{print $2}' | awk -F "\">" '{print $1}')
    curl -L -o "${DEST}/src/image/${CURRENT_RASPBIAN_FILE}" https://downloads.raspberrypi.org/raspios_lite_armhf/images/${CURRENT_RASPBIAN}/${CURRENT_RASPBIAN_FILE}
fi

