#!/usr/bin/env bash
if [ -z "$1" ];then
    pushd workspace
else
    pushd workspace-$1
fi

if [ -z "${CUSTOM_PI_OS_PATH}" ];then
    echo "Error: you must have \${CUSTOM_PI_OS_PATH} set"
    exit 1
fi

# source "${DIST_PATH}/config"
source "${CUSTOM_PI_OS_PATH}/config"

FILENAME=$(basename `ls . |  grep -e .img$ -e .raw$ | tail -n 1`)

if [ "${BASE_RELEASE_IMG_NAME}" == "default" ]; then
    if [ "${BASE_DISTRO}" == "ubuntu" ]; then
        CHANGE_STRING_LIST=( "ubuntu" )
    else
        CHANGE_STRING_LIST=( "raspbian" "raspios")
    fi

    # Handle variant name
    for CHANGE_STRING in "${CHANGE_STRING_LIST[@]}"
    do
        if [ -z "$1" ] || [ "$BASE_IGNORE_VARIANT_NAME" == "yes" ] ;then
            IMG_FILENAME=$(echo "${FILENAME::-4}"-"${DIST_VERSION}" | sed "s/${CHANGE_STRING}/${DIST_NAME,,}/").img
        else
            IMG_FILENAME=$(echo "${FILENAME::-4}"-"${DIST_VERSION}" | sed "s/${CHANGE_STRING}/${DIST_NAME,,}-$1/").img
        fi
    done
else
    IMG_FILENAME="${BASE_IMG_NAME}"
fi

mv "${FILENAME}" "${IMG_FILENAME}"

if [ "${BASE_RELEASE_COMPRESS}" == "yes" ]; then
    echo "Compressing image"
    if [ "${BASE_RELEASE_IMG_NAME}" == "default" ]; then
        zip "${IMG_FILENAME::-4}.zip" "${IMG_FILENAME}"
    else
        zip "${BASE_IMG_NAME%.zip}".zip "${IMG_FILENAME}"
    fi
else
    echo "Not compressing because setting is disabled"
fi

popd
