#!/usr/bin/env bash
# USBConsole
# Adds a console (getty) on the Raspberrys USB Port, useful for debugging headless setups without network
# Use minicom or Coolterm to access your PI (Note: This has only been tested on the RPI4)
# Written by Lukas Bachschwell
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap


echo "Enter usbconsole"
systemctl enable serial-getty@ttyGS0


# Note on raspberrypi gettys:
# for a serial getty go not use the getty@ services (like getty@ttyGS0)
# as these will hand when no device did connect to them and cause all kinds of funkey behaviour
# like not being able to reboot the device without force

echo "dtoverlay=dwc2" >> /boot/config.txt
echo "dwc2" >> /etc/modules
echo "g_serial" >> /etc/modules
 
